{{- range .Values.rtp_services }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
  labels:
    app-name: {{ .name }}-deployment 
spec:
  type: ClusterIP
  ports:
    - port: {{ .port | default "8080" }}
      targetPort: 8080
      protocol: TCP
      name: "8080"
  selector:
    app-name: {{ .name }} 

---
{{- end }}